name: On pull request

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"

env:
  DEFAULT_PYTHON: 3.11

jobs:
  python_checks:
    runs-on: ubuntu-latest
    name: Python Checks
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install requirements
        run: |
          python3 -m pip install -U pip
          python3 -m pip install ruff
      - name: Check formatting
        run: |
          ruff format --check --diff detector test
      - name: Check lint
        run: |
          ruff check detector test

  openvino_e2e_test:
    runs-on: ubuntu-latest
    name: OpenVINO E2E Test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install dependencies
        run: |
          python3 -m pip install -U pip
          # Replace onnxruntime with onnxruntime-openvino for testing
          sed -i 's/onnxruntime==/onnxruntime-openvino==/' requirements.txt
          python3 -m pip install -r requirements.txt
      - name: Run E2E Test
        run: |
          python3 test/test_e2e.py
